name: Restart Hugging Face Space

on:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  restart-space:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Space
        run: |
          curl -X POST https://api.huggingface.co/spaces/hank710535/River_Abnormal_Web/restart \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}"
